language: csharp
mono: none
dotnet: 3.0.100
dist: bionic
sudo: required

before_install:
  - wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O ~/packages-microsoft-prod.deb
  - sudo dpkg -i ~/packages-microsoft-prod.deb
  - sudo add-apt-repository universe
  - sudo apt-get update
  - sudo apt-get install apt-transport-https
  - sudo apt-get update
  - sudo apt-get install dotnet-sdk-2.1
  - dotnet tool install -g coveralls.net --version 1.0.0

install:
  - dotnet restore

script:
  - ./Scripts/BuildStage.sh
  - ./Scripts/TestStage.sh
  - ./Scripts/DeployStage.sh
